### ISSUE TITLE
CSS Fixes

### ISSUE THREAD

**Issue by kimardenmiller** [gomomentum/momentum_api#10]
@ryan-hyer , do these appeal to you?

- Light color in menu bar
![image](https://user-images.githubusercontent.com/2165336/61335056-f8c9d300-a7e0-11e9-9f51-3e540b47deec.png)
  
  Does not seem to be an issue on https://meta.discourse.org/

- Missing Blue box in email
![image](https://user-images.githubusercontent.com/2165336/61335180-6fff6700-a7e1-11e9-9d52-1dbfb1fee7f6.png)

  Does not seem to be an issue on https://meta.discourse.org/
    ![image](https://user-images.githubusercontent.com/2165336/61335238-a3da8c80-a7e1-11e9-8d95-9d38b6f06cae.png)

**Comment by kimardenmiller** [comment]
Do we think "Light color in menu bar" is still an issue on the latest version?

**Comment by ryan-hyer** [comment]
When I switch to dark mode, I still can't see the search icon or the hamburger icon without hovering over them. (Probably the biggest reason I still don't use dark mode.) I don't see anything in the 2.4.0.beta2 release notes that would be relevant, so yeah, I think it's still an issue. Still want me to poke into it?

**Comment by kimardenmiller** [comment]
That would be great. Notice on meta.discourse.org the problem does not seem to be there in dark mode.

/k

**Comment by ryan-hyer** [comment]
Blue box seems to be back. Must have been a temporary issue in an old version that has now been fixed. I have modified the CSS in the dark mode theme to make the header icons more visible.

**Comment by kimardenmiller** [comment]
Icons look great, Ryan. Thanks!

![image](https://user-images.githubusercontent.com/2165336/70181784-6e9ee000-1697-11ea-842c-b4f0c98da1e9.png)
