### ISSUE TITLE
Polls don't work from email

### ISSUE THREAD

**Issue by ryan-hyer** [gomomentum/momentum_api#11]
Brought to my attention by John Oberstar. Technologically, I don't think there's any way to make a poll work in an email notification. But perhaps there's a way to automate a warning message on emails with embedded polls, e.g. "This topic contains a poll. To vote in the poll, visit the topic on the website."

**Comment by kimardenmiller** [comment]
I think we need to move user behavior in the direction of understanding D is more like Facebook than Yahoo or Gmail. In some ways D almost does too much by email (much more than Facebook) to the point of making users imagine they can do everything by email. Doodle and Survey Monkey don't work by email. I guess D already makes a link to the poll. All I can imagine doing is expanding what that link says, *"Dude, click here to take this poll"*. 🙂

**Comment by ryan-hyer** [comment]
> users imagine they can do everything by email

Totally agree. This seems to be the fundamental misunderstanding behind almost all Discourse complaints, in one way or another.
