### ISSUE TITLE
Mailgun Discourse Mail Sending Optimization

### ISSUE THREAD

**Issue by kimardenmiller** [gomomentum/momentum_api#14]
@ryan-hyer would you be willing to have a look at these issues?

### mail-tester.com dings us for two main things:

1. No DMARC record

    A DMARC policy allows a sender to indicate that their emails are protected by SPF and/or DKIM, and give instruction if neither of those authentication methods passes. Please be sure you have a DKIM and SPF set before using DMARC.
You do not have a DMARC record, please add a TXT record to your domain _dmarc.discourse.gomomentum.org with the following value:

    v=DMARC1; p=none
    Verification details:

    mail-tester.com; dkim=pass (1024-bit key; unprotected) header.d=gomomentum.org 
    header.i=@gomomentum.org header.b=CRjtU4j1; dkim-atps=neutral
    mail-tester.com; dmarc=none header.from=discourse.gomomentum.org
    mail-tester.com; dkim=pass (1024-bit key; unprotected) header.d=gomomentum.org 
    header.i=@gomomentum.org header.b=CRjtU4j1; dkim-atps=neutral
    From Domain: discourse.gomomentum.org
    DKIM Domain: gomomentum.org

2. [Mailgun](https://www.whois365.com/en/ip/209.61.151.224?w365id=f2668e258e370822e91d424379ca0c01) shows on 1 blacklist. Can that be helped? 
  
    Matches your server IP address (209.61.151.224) against 25 of the most common IPv4 blacklists: SORBS (last 28 days)

**Comment by ryan-hyer** [comment]
The first one seems easy enough. I've never heard of DMARC, but if it's just adding a TXT entry to the DNS, I can do that.

The blacklist thing, I don't know that we can do much about, as long as we're using a third-party emailing service. Spammers will inevitably also use that service and get reported, blacklisting the whole thing.

**Comment by kimardenmiller** [comment]
Makes sense to solve the easy stuff first. The blacklist thing seems was not presenting before I moved off inallthings.xyz, so I wonder if Mailgun shifted us to a different mail server when I moved over to gomomentum.org. Seems worth asking them if we can get back to where we were / how to solve it. Must be something they are aware of.

**Comment by ryan-hyer** [comment]
Added a TXT entry in CloudFlare for DMARC. Try the tester again and see if it's resolved.

**Comment by kimardenmiller** [comment]
Nice work, @ryan-hyer                          ![bitmoji](https://render.bitstrips.com/v2/cpanel/88a46191-316c-43b7-b3de-b28ea745e607-e261621f-0963-48ce-be69-de6350c24849-v1.png?transparent=1&palette=1&width=246)

![image](https://user-images.githubusercontent.com/2165336/70182519-d275d880-1698-11ea-8438-28825f23d21e.png)
